import type { Resource } from './types';
const file=(resource_id:string, language_code:'en'|'it', file_name:string): NonNullable<Resource['resource_files']>[number] => ({id:`${resource_id}-${language_code}`,resource_id,language_code,language_label:language_code==='en'?'English':'Italiano',file_name,public_url:`/downloads/${file_name}`,mime_type:'application/pdf',file_format:'pdf',sort_order:language_code==='en'?1:2});
type CatalogRow=[string,string,string,string,string,Resource['access_level'],string[]];
const catalogRows: CatalogRow[] = [
['before-you-prompt-clarity-checklist','Before You Prompt: The Clarity Checklist','Define the objective, audience, context, inputs, constraints, and format before writing a prompt.','AI & Prompting','Checklist','public',['before-you-prompt-clarity-checklist.pdf','before-you-prompt-clarity-checklist_ITA.pdf']],
['one-prompt-framework','The One Prompt Framework You Actually Need','A reusable professional structure for almost any AI-assisted task.','AI & Prompting','Framework','public',['The_One_Prompt_Framework_AI_PM_Lab.pdf','The_One_Prompt_Framework_AI_PM_Lab_ITA.pdf']],
['vague-request-to-professional-prompt','From Vague Request to Professional Prompt','Before-and-after examples that turn unclear requests into usable instructions.','AI & Prompting','Practical Guide','public',['From_Vague_Request_to_Professional_Prompt_AI_PM_Lab.pdf','From_Vague_Request_to_Professional_Prompt_AI_PM_Lab_ITA.pdf']],
['professional-prompts-everyday-work','20 Professional Prompts for Everyday Work','Practical prompts for emails, documents, meetings, analysis, decisions, follow-ups, and planning.','AI & Prompting','Prompt Kit','free_member',['20_Professional_Prompts_for_Everyday_Work_AI_PM_Lab.pdf','20_Professional_Prompts_for_Everyday_Work_AI_PM_Lab_ITA.pdf']],
['instructions-improve-ai-answer','25 Instructions That Improve Almost Any AI Answer','Use critique, comparison, checklists, red teaming, summaries, and decision matrices.','AI & Prompting','Cheat Sheet','free_member',['25_Instructions_That_Improve_Almost_Any_AI_Answer_AI_PM_Lab.pdf','25_Instructions_That_Improve_Almost_Any_AI_Answer_AI_PM_Lab_ITA.pdf']],
['which-ai-tool-for-each-task','Which AI Tool Should You Use for Each Task?','Choose the right tool for writing, research, documents, data, images, code, and automation.','AI & Prompting','Tool Guide','free_member',['Which_AI_Tool_Should_You_Use_for_Each_Task_AI_PM_Lab.pdf']],
['ai-email-toolkit','The AI Email Toolkit','Templates for professional requests, reminders, follow-ups, refusals, and sensitive messages.','Professional Communication','Email Toolkit','free_member',['The_AI_Email_Toolkit_AI_PM_Lab.pdf','The_AI_Email_Toolkit_AI_PM_Lab_ITA.pdf']],
['write-like-a-human-with-ai','Write Like a Human with AI','Remove robotic language, generic phrases, unnecessary formality, and artificial tone.','Professional Communication','Writing Guide','free_member',['Write_Like_a_Human_with_AI_PM_Lab.pdf']],
['difficult-conversation-prompt-kit','The Difficult Conversation Prompt Kit','Prepare feedback, address delays, clarify responsibilities, and manage conflict.','Professional Communication','Prompt Kit','free_member',[]],
['client-follow-up-prompt-pack','Client Follow-Up Prompt Pack','Follow up after calls, proposals, events, presentations, and unanswered messages.','Professional Communication','Prompt Pack','free_member',['Client_Follow_Up_Prompt_Pack_AI_PM_Lab.pdf','Client_Follow_Up_Prompt_Pack_AI_PM_Lab_ITA.pdf']],
['client-call-to-tracked-task','From Client Call to Tracked Task','Turn client call notes into clear tracked tasks with owners, deadlines, status, and next actions.','Professional Communication','Workflow Guide','free_member',['From_Client_Call_to_Tracked_Task_AI_PM_Lab_EN.pdf','Dalla_Chiamata_al_Task_Tracciato_AI_PM_Lab_ITA.pdf']],
['create-install-codex-skill','Create & Install a Codex Skill','A bilingual practical guide for creating, installing, and using Codex skills in a repeatable workflow.','AI & Prompting','Skill Guide','free_member',['Guide_Create_Install_Codex_Skill_AI_PM_Lab_ENG.pdf','Guida_Creare_Installare_Skill_Codex_AI_PM_Lab_ITA.pdf']],
['turn-notes-into-documents','Turn Notes into Clear Professional Documents','Convert unstructured notes into emails, briefs, reports, procedures, and action plans.','Professional Communication','Document Builder','free_member',[]],
['prompts-think-like-consultant','30 Prompts to Think Like a Consultant','Apply pre-mortems, Pareto analysis, MECE, opportunity cost, five whys, and process audits.','Decisions & Business','Prompt Library','free_member',[]],
['validate-business-idea-with-ai','Validate Your Business Idea with AI','Examine the problem, customer, market, competitors, costs, risks, and first practical test.','Decisions & Business','Validation Guide','free_member',[]],
['understand-customers-with-ai','Understand Your Customers with AI','Identify customer needs, language, objections, channels, and assumptions that require validation.','Decisions & Business','Customer Analysis','free_member',[]],
['ai-research-fact-checking-checklist','The AI Research and Fact-Checking Checklist','Separate facts, assumptions, inferences, credible sources, and unverified information.','Decisions & Business','Checklist','free_member',[]],
['stakeholder-analysis-ai-pm-demo','Stakeholder Analysis AI + PM Demo','Download the demo package with Word, Excel, and PowerPoint files for a stakeholder analysis workflow created with AI and project management structure.','Decisions & Business','Demo Package','free_member',[]],
['ai-meeting-system','The AI Meeting System','Prepare meetings, capture decisions, assign actions, and manage professional follow-up.','Productivity & Organization','Operating System','free_member',[]],
['ai-action-plan-builder','The AI Action Plan Builder','Turn an objective into milestones, tasks, owners, deadlines, and completion criteria.','Productivity & Organization','Action Planner','free_member',[]],
['personal-weekly-review-with-ai','The Personal Weekly Review with AI','Review progress, blockers, unfinished work, changing priorities, and next actions.','Productivity & Organization','Weekly Review','free_member',[]],
['12-ai-workflows-for-small-teams','12 AI Workflows for Small Teams','Twelve practical AI-supported workflows to help small teams plan, communicate, organize work, and follow through.','Productivity & Organization','Workflow Guide','free_member',['12_AI_Workflows_for_Small_Teams_AI_PM_Lab.pdf','12_AI_Workflows_for_Small_Teams_AI_PM_Lab_ITA.pdf']],
['riforma-method','The RIFORMA Method','A practical bilingual guide to structure AI-assisted work with a clear repeatable method.','AI & Prompting','Method Guide','free_member',['The_RIFORMA_Method_AI_PM_Lab.pdf','Il_Metodo_RIFORMA_AI_PM_Lab_ITA.pdf']],
];
export const fallbackCatalog: Resource[] = catalogRows.map(([slug,title,description,category,resource_type,access_level,files],i)=>({id:slug,slug,title,description,category,resource_type,status:(files as string[]).length?'available':'coming_soon',access_level:access_level as Resource['access_level'],is_featured:i<3,sort_order:i+1,resource_files:(files as string[]).map((f,j)=>file(slug,j?'it':'en',f))}));
