import type { Profile, Resource, ResourceFile } from './types';
const url=import.meta.env.VITE_SUPABASE_URL as string|undefined; const key=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string|undefined;
export const isSupabaseConfigured=Boolean(url&&key);
type Session={access_token:string; user:{id:string}};
const sessionKey='ai-pm-library-session';
const headers=(token?:string)=>({'apikey':key!,Authorization:`Bearer ${token||key!}`,'Content-Type':'application/json'});
const request=async<T>(path:string, init:RequestInit={},token?:string)=>{if(!isSupabaseConfigured)throw new Error('Library access is not configured yet.'); const r=await fetch(`${url}${path}`,{...init,headers:{...headers(token),...init.headers}}); if(!r.ok)throw new Error('Unable to complete this request.'); return r.json() as Promise<T>};
export const supabase={auth:{getSession:async()=>({data:{session:JSON.parse(localStorage.getItem(sessionKey)||'null') as Session|null}}),signInAnonymously:async()=>{const data=await request<Session>('/auth/v1/signup',{method:'POST',body:JSON.stringify({})});localStorage.setItem(sessionKey,JSON.stringify(data));return {data:{user:data.user,session:data},error:null};},signOut:async()=>{const s=JSON.parse(localStorage.getItem(sessionKey)||'null') as Session|null;if(s)await request('/auth/v1/logout',{method:'POST'},s.access_token).catch(()=>undefined);localStorage.removeItem(sessionKey);},onAuthStateChange:(callback:()=>void)=>{const f=(e:StorageEvent)=>{if(e.key===sessionKey)callback()};window.addEventListener('storage',f);return {data:{subscription:{unsubscribe:()=>window.removeEventListener('storage',f)}}}}},
 getProfile:async(session:Session)=>{const rows=await request<Profile[]>(`/rest/v1/profiles?id=eq.${session.user.id}&select=*`,{},session.access_token);return rows[0]||null},
 saveProfile:async(session:Session,profile:Omit<Profile,'id'|'membership_tier'|'last_access_at'>)=>request('/rest/v1/profiles?on_conflict=id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify({id:session.user.id,...profile,membership_tier:'free',last_access_at:new Date().toISOString()})},session.access_token),
 catalog:async(session?:Session|null)=>{const rows=await request<Resource[]>('/rest/v1/resources?select=*&order=sort_order.asc',{},session?.access_token);const files=await request<ResourceFile[]>('/rest/v1/resource_files?select=*&order=sort_order.asc',{},session?.access_token);return rows.map(r=>({...r,resource_files:files.filter(f=>f.resource_id===r.id)}));},
 activity:async(session:Session,resource_id:string,event_type:'view'|'open'|'download'|'save'|'unsave',resource_file_id?:string)=>request('/rest/v1/resource_activity',{method:'POST',body:JSON.stringify({user_id:session.user.id,resource_id,resource_file_id,event_type})},session.access_token),
 bookmarks:async(session:Session)=>request<{resource_id:string}[]>('/rest/v1/resource_bookmarks?select=resource_id',{},session.access_token),
 toggleBookmark:async(session:Session,resource_id:string,saved:boolean)=>saved?request(`/rest/v1/resource_bookmarks?user_id=eq.${session.user.id}&resource_id=eq.${resource_id}`,{method:'DELETE'},session.access_token):request('/rest/v1/resource_bookmarks',{method:'POST',body:JSON.stringify({user_id:session.user.id,resource_id})},session.access_token)
};
