import React from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useAuth } from '../auth/AuthProvider';
import { fallbackCatalog } from '../lib/catalog';
import { supabase } from '../lib/supabase';
import type { Resource } from '../lib/types';

const tabs = ['Overview', 'Free Library', 'Premium Library', '1:1 Sessions', 'Saved Resources', 'My Account'] as const;
type Tab = typeof tabs[number];

const consultingPhases = [
  ['00', 'FREE WORKFLOW CLARITY CALL', 'Find the right activity and understand the wider problem.', 'We review one recurring activity, how it currently works, where it breaks, and what other people, documents, decisions, or follow-ups depend on it.', 'YOU LEAVE WITH', 'Fit assessment, priority workflow, and recommended next step'],
  ['01', 'FOCUS', 'Choose the activity that can create the most useful improvement.', 'We identify the recurring activity where lost time, unclear information, inconsistent outputs, or missed follow-up create the greatest operational impact.', 'YOU RECEIVE', 'Priority Workflow Brief'],
  ['02', 'MAP', 'Connect the activity to the complete project around it.', 'We map inputs, people, responsibilities, documents, decisions, dependencies, risks, handoffs, and next actions.', 'YOU RECEIVE', 'Current-State Workflow Map and Project Context'],
  ['03', 'DESIGN', 'Define how the work should operate from start to finish.', 'We establish clear steps, ownership, completion criteria, review points, communication needs, and where AI can provide practical support.', 'YOU RECEIVE', 'Future-State Workflow Blueprint and Ownership Structure'],
  ['04', 'BUILD AND TEST', 'Create the system and use it on real work.', 'We build the prompts, templates, tracker, document structure, SOP, communication routine, or review checklist needed for the workflow. Then we test and correct it.', 'YOU RECEIVE', 'Tested Workflow Prototype and Human Review Process'],
  ['05', 'INTEGRATE AND SCALE', 'Put the system into the project and prepare the next expansion.', 'We document the process, define measures, connect it to related project activities, and identify what workflow should be improved next.', 'YOU RECEIVE', 'Working Project System and 30-Day Scale Plan'],
] as const;

function LibrarySidebar({ active, onChange, username, onLogout }: { active: Tab; onChange: (tab: Tab) => void; username: string; onLogout: () => void }) {
  const [open, setOpen] = React.useState(false);
  const choose = (tab: Tab) => { onChange(tab); setOpen(false); };
  return <>
    <button className="library-mobile-launcher" type="button" aria-label="Open Library navigation" aria-expanded={open} onClick={() => setOpen(true)}><span>Library</span><span aria-hidden="true">☰</span></button>
    {open && <button className="library-menu-backdrop" type="button" aria-label="Close Library navigation" onClick={() => setOpen(false)} />}
    <aside className={`library-sidebar ${open ? 'is-open' : ''}`} aria-label="Library navigation">
      <div className="library-sidebar-brand"><span>AI PM LAB</span><small>Resource Library</small><button className="library-mobile-close" type="button" aria-label="Close Library navigation" onClick={() => setOpen(false)}>×</button></div>
      <nav className="library-nav" aria-label="Member dashboard sections">{tabs.map((tab) => <button type="button" className={active === tab ? 'active' : ''} key={tab} onClick={() => choose(tab)}>{tab}</button>)}</nav>
      <div className="library-member-mini"><span>Free Member</span><strong>@{username}</strong></div>
      <button className="library-signout" type="button" onClick={onLogout}>Sign out</button>
    </aside>
  </>;
}

function ResourceCards({ resources, saved, onToggle, onDownload }: { resources: Resource[]; saved: string[]; onToggle: (resource: Resource) => void; onDownload: (resource: Resource, fileId: string) => void }) {
  return <div className="library-grid">{resources.map((resource) => <article className="library-resource-card" key={resource.id}>
    <div className="library-resource-top"><div><span className="library-badge">{resource.category}</span><span className="library-type">{resource.resource_type}</span></div><button className={saved.includes(resource.id) ? 'library-save saved' : 'library-save'} type="button" onClick={() => onToggle(resource)}>{saved.includes(resource.id) ? 'Saved' : 'Save'}</button></div>
    <h3>{resource.title}</h3><p>{resource.description}</p>
    <footer>{resource.status === 'available' ? (resource.resource_files ?? []).map((file) => <a className="library-download" key={file.id} href={file.public_url} download onClick={() => onDownload(resource, file.id)}>{file.language_code === 'it' ? '🇮🇹 PDF Italiano' : '🇺🇸 English PDF'} <span>↓</span></a>) : <span className="library-status">Coming Soon</span>}</footer>
  </article>)}</div>;
}

function ConsultingJourney() {
  return <section className="library-journey">
    <div className="library-journey-intro"><p className="eyebrow">THE 1:1 CONSULTING JOURNEY</p><h1>One free call.<span>Five phases.</span>Your project system takes shape.</h1><p>These are not generic AI lessons. Each phase advances a real workflow inside your business or project.</p><p>We begin with one recurring activity, connect it to the wider project, build the necessary system, test it on real work, and prepare it for continued use.</p></div>
    <div className="library-phase-list">{consultingPhases.map(([number, label, title, copy, resultLabel, result]) => <article className="library-phase" key={number}><div className="library-phase-number">{number}</div><div className="library-phase-copy"><p>{label}</p><h3>{title}</h3><span>{copy}</span></div><div className="library-phase-result"><p>{resultLabel}</p><strong>{result}</strong></div></article>)}</div>
    <div className="library-system-callout"><div><p className="eyebrow">THE RESULT</p><h2>Your own practical AI + Project Management system.</h2><p>Not a collection of prompts. A tested working system built around your activity: instructions, templates, trackers, documents, ownership, review points, and a routine your team can actually use.</p></div><a className="button light" href="https://calendly.com/propertydext/15min" target="_blank" rel="noreferrer">Book a Free Workflow Clarity Call</a></div>
  </section>;
}

function Onboarding(){
  const{session,profile,refresh}=useAuth();const[username,setUsername]=React.useState(profile?.username||'');const[privacy,setPrivacy]=React.useState(false);const[marketing,setMarketing]=React.useState(profile?.marketing_consent||false);const[error,setError]=React.useState('');const[success,setSuccess]=React.useState('');const[saving,setSaving]=React.useState(false);const errorRef=React.useRef<HTMLParagraphElement>(null);
  React.useEffect(()=>{if(error)errorRef.current?.focus()},[error]);
  const submit=async(event:React.FormEvent)=>{event.preventDefault();setError('');setSuccess('');const candidate=username.trim();if(candidate.length<2||candidate.length>40){setError('Choose a username between 2 and 40 characters.');return}if(!privacy){setError('Please accept the Resource Library Privacy Notice to continue.');return}if(!session||!profile){setError('Your session is no longer available. Please sign in again.');return}setSaving(true);try{const available=await supabase.rpc('is_username_available',{candidate});if(available.data!==true&&candidate.toLowerCase()!==profile.username.toLowerCase()){setError('That username is already in use. Please choose another one.');return}await supabase.saveProfile(session,{username:candidate,marketing_consent:marketing,privacy_accepted_at:new Date().toISOString(),auth_provider:'google',onboarding_completed:true});setSuccess('Your Library profile is ready. Opening your dashboard…');await refresh()}catch(technicalError){console.error('Unable to save Library onboarding profile',technicalError);setError('We could not save your Library profile. Please try again.')}finally{setSaving(false)}};
  return <main className="library-onboarding-shell"><form className="library-onboarding-card" onSubmit={submit}><div className="onboarding-heading"><p className="onboarding-step">Step 1 of 1 · Complete your profile</p><p className="eyebrow">COMPLETE YOUR MEMBER PROFILE</p><h1>One final step before opening your Library.</h1><p>Your Google account is verified. Choose the username you want to use inside AI PM LAB and confirm your Library preferences.</p></div><section className="onboarding-group"><p className="onboarding-group-label">SIGNED IN WITH GOOGLE</p><div className="onboarding-identity"><div><span>Display name</span><strong>{profile?.display_name||'Google member'}</strong></div><div><span>Verified email</span><strong>{profile?.email||session?.user.email||''}</strong></div></div></section><section className="onboarding-group"><p className="onboarding-group-label">CREATE YOUR LIBRARY PROFILE</p><label htmlFor="library-username">Choose your Library username<input id="library-username" value={username} onChange={e=>setUsername(e.target.value)} autoComplete="username" disabled={saving}/></label><small>Use 2–40 characters. You can change it later in My Account.</small></section><section className="onboarding-group onboarding-preferences"><p className="onboarding-group-label">PREFERENCES</p><label className="check"><input type="checkbox" checked={privacy} onChange={e=>setPrivacy(e.target.checked)} disabled={saving}/>I agree to the <Link to="/resource-library-privacy-notice">Resource Library Privacy Notice</Link>.</label><label className="check"><input type="checkbox" checked={marketing} onChange={e=>setMarketing(e.target.checked)} disabled={saving}/>Send me occasional AI PM LAB resources, templates, and Library updates <em>(optional)</em>.</label></section>{error&&<p className="onboarding-error" role="alert" tabIndex={-1} ref={errorRef}>{error}</p>}{success&&<p className="onboarding-success" role="status">{success}</p>}<button className="button primary" type="submit" disabled={saving}>{saving?'Opening your Library…':'Open my Library'}</button></form></main>}


function Account(){const{profile,session,refresh,signOut}=useAuth();const[username,setUsername]=React.useState(profile?.username||'');const[marketing,setMarketing]=React.useState(profile?.marketing_consent||false);const[message,setMessage]=React.useState('');return <div className="library-account"><p className="eyebrow">MEMBER PROFILE</p><h1>My Account</h1><label>Username<input value={username} onChange={e=>setUsername(e.target.value)}/></label><label>Verified email<input readOnly value={profile?.email||session?.user.email||''}/></label><div className="library-account-note"><strong>Authentication method:</strong> {profile?.auth_provider==='google'?'Google':'Email'}<br/><strong>Membership:</strong> {profile?.membership_tier||'free'} Member</div><label className="check"><input type="checkbox" checked={marketing} onChange={e=>setMarketing(e.target.checked)}/>Receive occasional Library updates <em>(optional)</em>.</label><button className="button primary" onClick={async()=>{if(!session||!profile)return;const check=await supabase.rpc('is_username_available',{candidate:username.trim()});if(check.data!==true&&username.trim().toLowerCase()!==profile.username.toLowerCase())return setMessage('That username is not available.');await supabase.saveProfile(session,{username:username.trim(),marketing_consent:marketing});await refresh();setMessage('Profile updated.')}}>Save profile</button>{message&&<p>{message}</p>}<button className="button secondary" onClick={()=>void signOut()}>Sign out</button></div>}

function LocalAccount({ username, onLogout }: { username: string; onLogout: () => void }) {
  return <div className="library-account"><p className="eyebrow">MEMBER PROFILE</p><h1>My Account</h1><label>Username<input readOnly value={username} /></label><div className="library-account-note"><strong>Authentication method:</strong> Library membership<br/><strong>Membership:</strong> Free Member</div><button className="button secondary" onClick={onLogout}>Sign out</button></div>;
}

export function Library() {
  const { loading, profileLoading, session, profile, signOut } = useAuth(); const navigate = useNavigate(); const [tab, setTab] = React.useState<Tab>('Overview'); const [items, setItems] = React.useState<Resource[]>(fallbackCatalog); const [saved, setSaved] = React.useState<string[]>([]); const [query, setQuery] = React.useState('');
  const hasLocalAccess = supabase.hasLibraryAccess(); const hasAccess = hasLocalAccess || Boolean(session);
  const localUsername = 'member';
  React.useEffect(() => { if (!loading && !hasAccess) navigate('/resources?access=required'); if (!loading && session && !profile) navigate('/resources#library-access'); }, [hasAccess, loading, navigate, profile, session]);
  React.useEffect(() => { if (session) { void supabase.catalog(session).then(setItems).catch(() => undefined); void supabase.bookmarks(session).then((rows) => setSaved(rows.map((row) => row.resource_id))).catch(() => undefined); } }, [session]);
  if ((loading && !hasLocalAccess) || !hasAccess || (session && profileLoading)) return <div className="library-loading">Preparing your Library…</div>;
  if (session && !profile) return <div className="library-loading">Finishing your Library profile…</div>;
  if (session && profile && profile.onboarding_completed === false) return <Onboarding />;
  const toggle = async (resource: Resource) => { const isSaved = saved.includes(resource.id); if (session) { await supabase.toggleBookmark(session, resource.id, isSaved); await supabase.activity(session, resource.id, isSaved ? 'unsave' : 'save'); } setSaved((current) => isSaved ? current.filter((id) => id !== resource.id) : [...current, resource.id]); };
  const download = (resource: Resource, fileId: string) => { if (session) void supabase.activity(session, resource.id, 'download', fileId); };
  const logout = async () => { await signOut(); navigate('/resources'); };
  const username = profile?.username || localUsername;
  const filtered = items.filter((resource) => `${resource.title} ${resource.description} ${resource.category}`.toLowerCase().includes(query.toLowerCase()));
  let content: React.ReactNode;
  if (tab === 'Overview') content = <><section className="library-welcome"><p className="eyebrow">MEMBER OVERVIEW</p><h1>Welcome back, <span>@{username}</span></h1><p>Your calm space for practical tools, useful references, and the next step in building a better workflow.</p><div className="library-welcome-actions"><button className="button light" onClick={() => setTab('Free Library')}>Browse the Library</button><button className="library-text-button" onClick={() => setTab('1:1 Sessions')}>Explore the 1:1 journey →</button></div></section><section className="library-overview-grid"><article><span>START HERE</span><h3>Before You Prompt: The Clarity Checklist</h3><p>Use one clear framework before you ask AI to do the work.</p><button onClick={() => setTab('Free Library')}>Open resource library →</button></article><article><span>YOUR TOOLKIT</span><strong>{saved.length}</strong><p>Saved resources ready to revisit.</p><button onClick={() => setTab('Saved Resources')}>View saved resources →</button></article><article><span>ACCESS</span><h3>Free Library</h3><p>Active on this browser. Premium tools can be added later.</p></article></section></>;
  else if (tab === 'Free Library') content = <><div className="library-page-heading"><div><p className="eyebrow">FREE LIBRARY</p><h1>Practical tools for real work.</h1></div><input aria-label="Search the Library" placeholder="Search resources" value={query} onChange={(event) => setQuery(event.target.value)} /></div><ResourceCards resources={filtered} saved={saved} onToggle={(resource) => void toggle(resource)} onDownload={download} /></>;
  else if (tab === 'Saved Resources') content = <><div className="library-page-heading"><div><p className="eyebrow">PERSONAL TOOLKIT</p><h1>Saved resources</h1></div></div>{saved.length ? <ResourceCards resources={items.filter((resource) => saved.includes(resource.id))} saved={saved} onToggle={(resource) => void toggle(resource)} onDownload={download} /> : <div className="library-empty"><h2>Your toolkit starts here.</h2><p>Save useful resources to build your personal AI PM LAB toolkit.</p><button className="button primary" onClick={() => setTab('Free Library')}>Browse resources</button></div>}</>;
  else if (tab === 'Premium Library') content = <div className="library-empty"><p className="eyebrow">FUTURE ACCESS</p><h1>Premium tools can be added here when protected delivery and payments are introduced.</h1><p>Future premium resources may include editable workflow packs, advanced templates, implementation tools, and sector-specific systems.</p><button className="button primary" onClick={() => setTab('My Account')}>Request Premium Updates</button></div>;
  else if (tab === '1:1 Sessions') content = <ConsultingJourney />;
  else content = session && profile ? <Account /> : <LocalAccount username={username} onLogout={() => void logout()} />;
  return <div className="library-dashboard"><LibrarySidebar active={tab} onChange={setTab} username={username} onLogout={() => void logout()} /><main className="library-main"><header className="library-topbar"><div><span>AI PM LAB</span><small>Member Library</small></div><strong>Free Member</strong></header>{content}</main></div>;
}
